import requests
import time
import random

# ======================
# 🔧 TELEGRAM CONFIGURATION
# ======================

# 👉 Apna Telegram bot token yaha daale (BotFather se mila hua)
TOKEN = "PASTE_YOUR_TELEGRAM_BOT_TOKEN_HERE"

# 👉 Apna chat id yaha daale (ye tu ne diya: 7651539791)
CHAT_ID = "7651539791"

# ======================
# ⚙️ FUNCTION TO SEND MESSAGE
# ======================
def send_telegram_message(message):
    url = f"https://api.telegram.org/bot{TOKEN}/sendMessage"
    data = {"chat_id": CHAT_ID, "text": message}
    try:
        response = requests.post(url, data=data)
        if response.status_code == 200:
            print("✅ Message sent successfully!")
        else:
            print("⚠️ Failed to send message:", response.text)
    except Exception as e:
        print("❌ Error:", e)

# ======================
# 🤖 SIMULATED AI TRADING LOGIC (LATER ADD REAL MODEL)
# ======================
def trading_signal():
    # Randomly simulate AI signal (later replace with real model)
    signals = ["BUY", "SELL", "HOLD"]
    signal = random.choice(signals)
    confidence = round(random.uniform(80, 99), 2)
    
    # Create message
    message = f"📈 AI Trading Signal Alert\n\nSignal: {signal}\nConfidence: {confidence}%\n\n📊 This signal is auto-generated by AI v2.0"
    
    # Send Telegram alert
    send_telegram_message(message)

# ======================
# 🚀 MAIN LOOP (RUN FOREVER)
# ======================
print("🤖 AI Trading Alert Bot is now running... (sends signal every 10 minutes)")
while True:
    trading_signal()
    time.sleep(600)  # wait 10 minutes
